import { useEffect, useState } from "react";
import { Download, Loader2, RefreshCw, Store } from "lucide-react";
import AppShell from "@/components/AppShell";
import { requireSupabase } from "@/lib/supabase";

type Product = { id: string; title: string; description: string; category: string; price: number; currency: string };
export default function Marketplace() {
  const [products, setProducts] = useState<Product[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const { data, error } = await requireSupabase().from("products").select("id,title,description,category,price,currency").eq("active", true).order("created_at", { ascending: false }); if (error) throw error; setProducts((data ?? []) as Product[]); } catch (e) { setError(e instanceof Error ? e.message : "Marketplace is not configured yet."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const visible = products.filter((p) => `${p.title} ${p.description} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
  return <AppShell current="/marketplace"><div className="app-page-head"><div><span className="kicker"><Store size={13} /> Aegis / Marketplace</span><h1>Defensive tools, responsibly listed.</h1><p>Legitimate security utilities, templates, documentation, and authorized testing resources. Aegis takes 5% only on eligible transactions completed through the platform.</p></div><button className="button button--outline-dark button--small" type="button" onClick={() => void load()} disabled={loading}>{loading ? <Loader2 className="spin" size={14} /> : <RefreshCw size={14} />} Refresh</button></div><div className="filters" style={{ marginBottom: 14 }}><input aria-label="Search marketplace" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search products" /></div>{error && <section className="panel"><div className="empty-state empty-state--error"><h3>Marketplace configuration required</h3><p>{error}</p></div></section>}{!error && loading && <section className="panel"><div className="empty-state"><Loader2 className="spin" size={20} /><p>Loading published products…</p></div></section>}{!error && !loading && visible.length === 0 && <section className="panel"><div className="empty-state"><Download size={22} /><h3>{products.length ? "No matching products" : "Marketplace is ready for creators"}</h3><p>{products.length ? "Try a different search." : "Published, moderated products will appear here. No inventory or payment is simulated."}</p></div></section>}{!error && visible.length > 0 && <section className="panel-grid panel-grid--3">{visible.map((product) => <article className="panel" key={product.id}><div className="panel__body"><span className="kicker">{product.category}</span><h2 className="panel__title" style={{ marginTop: 10 }}>{product.title}</h2><p className="panel__note">{product.description}</p><strong style={{ display: "block", marginTop: 18 }}>{product.currency === "INR" ? "₹" : product.currency} {product.price.toLocaleString()}</strong><p className="panel__note">Checkout will activate after a payment provider is configured.</p></div></article>)}</section>}</AppShell>;
}
