import { useEffect, useState } from "react";
import { FolderKanban, Loader2, RefreshCw } from "lucide-react";
import AppShell from "@/components/AppShell";
import { requireSupabase } from "@/lib/supabase";

type Project = { id: string; title: string; requirements: string; status: string; budget: number | null; deadline: string | null; created_at: string };
export default function Projects() {
  const [rows, setRows] = useState<Project[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const client = requireSupabase(); const { data: auth } = await client.auth.getUser(); if (!auth.user) throw new Error("Your session has expired."); const { data, error } = await client.from("projects").select("id,title,requirements,status,budget,deadline,created_at").eq("client_id", auth.user.id).order("created_at", { ascending: false }); if (error) throw error; setRows((data ?? []) as Project[]); } catch (e) { setError(e instanceof Error ? e.message : "Projects are not available yet."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <AppShell current="/projects"><div className="app-page-head"><div><span className="kicker"><FolderKanban size={13} /> Workspace / Projects</span><h1>My Projects</h1><p>Requests and engagements stay here from initial scope through delivery.</p></div><button className="button button--outline-dark button--small" type="button" onClick={() => void load()} disabled={loading}>{loading ? <Loader2 className="spin" size={14} /> : <RefreshCw size={14} />} Refresh</button></div>{error && <section className="panel"><div className="empty-state empty-state--error"><h3>Projects need configuration</h3><p>{error}</p></div></section>}{!error && loading && <section className="panel"><div className="empty-state"><Loader2 className="spin" size={20} /><p>Loading your projects…</p></div></section>}{!error && !loading && rows.length === 0 && <section className="panel"><div className="empty-state"><FolderKanban size={22} /><h3>No projects yet</h3><p>When you request a service, the project workspace will appear here.</p><a className="button button--lime button--small" href="/services">Browse services</a></div></section>}{!error && !loading && rows.length > 0 && <section className="panel-grid panel-grid--2">{rows.map((project) => <article className="panel" key={project.id}><div className="panel__head"><h2 className="panel__title">{project.title}</h2><span className="badge-note">{project.status.replaceAll("_", " ")}</span></div><div className="panel__body"><p className="panel__note">{project.requirements}</p><div className="field-row" style={{ marginTop: 14 }}><span className="field-row__label">Created</span><p className="field-row__hint">{new Date(project.created_at).toLocaleDateString()}</p></div>{project.deadline && <div className="field-row"><span className="field-row__label">Target deadline</span><p className="field-row__hint">{project.deadline}</p></div>}</div></article>)}</section>}</AppShell>;
}
